language: ruby
rvm:
  - 2.4.1
  - 2.4.0
service:
  - mysql
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
script:
  - ls
  - bundle exec rubocop -c .rubocop.yml
  - bundle exec rails spec
