language: ruby
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
rvm:
- 2.4.1
- 2.4.0
service:
- mysql
before_script:
- |
  sudo apt-get remove --purge "^mysql.*"
  sudo apt-get autoremove
  sudo apt-get autoclean
  sudo rm -rf /var/lib/mysql
  sudo rm -rf /var/log/mysql
  echo mysql-apt-config mysql-apt-config/enable-repo select mysql-5.7-dmr | sudo debconf-set-selections
  wget http://dev.mysql.com/get/mysql-apt-config_0.2.1-1ubuntu12.04_all.deb
  sudo dpkg --install mysql-apt-config_0.2.1-1ubuntu12.04_all.deb
  sudo apt-get update -q
  sudo apt-get install -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" mysql-server
- |
  echo -e "[mysqld]
  character_set_server=utf8mb4
  collation_server=utf8mb4_unicode_ci
  innodb_large_prefix=ON
  innodb_file_format=Barracuda
  innodb_file_format_max=Barracuda" | sudo tee /etc/mysql/conf.d/travis.cnf
- sudo /etc/init.d/mysql restart
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- ls
- bundle exec rubocop -c .rubocop.yml
- bundle exec rails spec
notifications:
  slack:
    secure: AUvEfJDsBV1nPAxUXNOtt7Sbt02NBv5Y3AZEr7fT+tYhAB3ES3c8qa9cZQhQ8oSluxLsm2LZeGcZeKDOWlIeNZaJnigxYSX7Myt6tLkfc6JCXvcxQHzGgxNP8qr2R0wcjdH83Uy5134ELbovxEzi3PGXqn5wuMnlUJu3GUbgO8zo6qXi+iJGGnt8E2v1b1/dKa8BmChHBl/52TM5yULKnTz/sv8COXUGhU0u2R2D+EGDOcNmbjBYfNxSj7JAu9y9Yp6zek7V5UPDm4bmOilYCpHTF/Ho45KpbpZvgl/0olzLJMkcjoDwZDwvXauTXjxz5O/4sR2cNjVPvtQ/kJUn7mdOETICSzk/78Oy2q1D8CnOSXJRi2fjgAzN7XTceoMv59Fnw90y4GhmvOmcr4Am0w41htNKMin5JmWPIc4ZnY2GV2TJdIAHb7FfXmATzrhUDTmz0u8N+RdAJ0eWV+zgHSGz4nh5nX5bLm8WNMxM9Cmim/UsoEBjDR6aQnmKGoWLLWdJh3d9EBDHxOeoKiAIlRe9l915P3xw66pqbtIylziYOzIOynxqLZgzcBqbL6tzpuRejaR0QISb1F17RvUIWkFS2biKK6ICpjDMEuBpdWIOFd1IHR4bPSNzzgnkrqHxogkDqGuZ2ILsOjYsZo8i3DKbsicvrx+y6/kixdIOdCU=
